SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT * ,
        RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS R
        
    FROM REST_INFO
) AS R_TABLE
WHERE R = 1
ORDER BY FOOD_TYPE DESC;