WITH 
target AS (
    SELECT CAR_ID, START_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01'
      AND START_DATE < '2022-11-01'
),

popular_cars AS (
    SELECT CAR_ID
    FROM target
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)

SELECT
    MONTH(t.START_DATE) AS MONTH,
    t.CAR_ID  AS CAR_ID,
    COUNT(*) AS RECORDS
FROM target AS t
JOIN popular_cars AS p ON p.CAR_ID = t.CAR_ID
GROUP BY MONTH(t.START_DATE), t.CAR_ID
ORDER BY MONTH ASC, t.CAR_ID DESC;
